[base]
timezone = "UTC"
admins = []
debug = false

[database]
path = "ggp.sqlite"
query_timeout = 5  # in seconds

[fetcher]
period = 300  # in seconds
token = "auth_token"
url = ""  # http(s) url to data source

[telegram]
token = "bot_token"
