[base]
timezone = "UTC"
admins = []
debug = false

[database]
path = "ggp.sqlite"
query_timeout = 5  # in seconds
threads = 1  # number of database threads

[fetcher]
active = true
period = 300  # in seconds
token = "auth_token"
url = ""  # JSON http(s) url to data source

[holidayer]
active = true
period = 86400  # in seconds, 1 day
url = ""  # XML http(s) url to data source, year is <YEAR> string

[predictor]
active = true
hours = 4
load_size = 1000
query_timeout = 10  # in seconds

[telegram]
active = true
token = "bot_token"
